### PR TITLE
JAM-17, JAM-65:  Created component to create new products. CSS consolidation.

### PR DESCRIPTION
**Pull request by fjnw**
- ReadMe/package.json/yarn.lock reflects new package:  react-datepicker. 
- NavBar links reorganized and added "Logout" button.
- QA component redone.
- Small changes to signup based on group input from 2/19. Small changes to other components.
- Component for new product created.

### CODE REVIEW

**Comment by fjnw** [comment]
Change merge title to... 
JAM-16, JAM-17, JAM-65: Created components to view product and create new products. CSS consolidation.

**Review by AndrewD14 — CHANGES_REQUESTED** [review]
I pulled your code and I am seeing this on account page:
image

**Review by AndrewD14 — APPROVED** [review]

**Review by AndrewD14 — APPROVED** [review]
I have reviewed the change and the issue is gone on the account page.

Just need to be aware that the hover-over coloring seems to highlight both buttons on the add url and add img on the product-new page.

**Comment by AndrewD14** [comment]
Love the new form look for the product and login.

**Pull request merged**
